name: mac-package

on:
  workflow_dispatch:

jobs:
  package-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: |
            export HOMEBREW_NO_AUTO_UPDATE=true
            brew install create-dmg tree

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x

      - name: Install dotnet workload and dependencies
        working-directory: ./src/KimonoMac
        run: |
            dotnet workload install macos
            dotnet workload restore
            dotnet restore

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: 15.*

      - name: Build
        working-directory: ./src/KimonoMac
        run: |
            dotnet build -c Release -p:PublishAot=true

      - name: Package
        working-directory: ./src/KimonoMac/bin/Release/net8.0-macos
        run: |
            dotnet build -c Release -p:PublishAot=true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "KimonoMac.dmg"
          path: ./src/KimonoMac/bin/Release/net8.0-macos/KimonoMac.dmg
